## Cleanig the Global Weather Data

In [1]:
##Import Libraries
import pandas as pd
import numpy as np

df = pd.read_csv("Global_Weather_Repository.csv")

In [2]:
##Check Data
print(df.shape)
df.head()

(166838, 41)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [3]:
## Check information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166838 entries, 0 to 166837
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       166838 non-null  object
 1   location_name                 166838 non-null  object
 2   latitude                      166838 non-null  float64
 3   longitude                     166838 non-null  float64
 4   timezone                      166838 non-null  object
 5   last_updated_epoch            166838 non-null  int64
 6   last_updated                  166838 non-null  object
 7   temperature_celsius           166838 non-null  float64
 8   temperature_fahrenheit        166838 non-null  float64
 9   condition_text                166838 non-null  object
 10  wind_mph                      166838 non-null  float64
 11  wind_kph                      166838 non-null  float64
 12  wind_degree                   166838 non-null  int64
 13  wind_direction                166838 non-null  object
 14  pressure_mb                   166838 non-null  float64
 15  pressure_in                   166838 non-null  float64
 16  precip_mm                     166838 non-null  float64
 17  precip_in                     166838 non-null  float64
 18  humidity                      166838 non-null  int64
 19  cloud                         166838 non-null  int64
 20  feels_like_celsius            166838 non-null  float64
 21  feels_like_fahrenheit         166838 non-null  float64
 22  visibility_km                 166838 non-null  float64
 23  visibility_miles              166838 non-null  float64
 24  uv_index                      166838 non-null  float64
 25  gust_mph                      166838 non-null  float64
 26  gust_kph                      166838 non-null  float64
 27  air_quality_Carbon_Monoxide   166838 non-null  float64
 28  air_quality_Ozone             166838 non-null  float64
 29  air_quality_Nitrogen_dioxide  166838 non-null  float64
 30  air_quality_Sulphur_dioxide   166838 non-null  float64
 31  air_quality_PM2.5             166838 non-null  float64
 32  air_quality_PM10              166838 non-null  float64
 33  air_quality_us-epa-index      166838 non-null  int64
 34  air_quality_gb-defra-index    166838 non-null  int64
 35  sunrise                       166838 non-null  object
 36  sunset                        166838 non-null  object
 37  moonrise                      166838 non-null  object
 38  moonset                       166838 non-null  object
 39  moon_phase                    166838 non-null  object
 40  moon_illumination             166838 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 52.2+ MB

In [4]:
## Check Null Values
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [5]:
## Check Duplicates
df.duplicated().sum()

np.int64(0)

In [6]:

df.describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,166838.0,1.927504e+01,2.437892e+01,-4.130000e+01,4.050300e+00,1.725000e+01,4.040000e+01,6.530000e+01
longitude,166838.0,2.182161e+01,6.576936e+01,-1.752000e+02,-6.836100e+00,2.143330e+01,4.988220e+01,1.792200e+02
last_updated_epoch,166838.0,1.752981e+09,2.143652e+07,1.715849e+09,1.734432e+09,1.753000e+09,1.771570e+09,1.790057e+09
temperature_celsius,166838.0,2.146548e+01,9.312467e+00,-2.980000e+01,1.620000e+01,2.370000e+01,2.770000e+01,7.930000e+01
temperature_fahrenheit,166838.0,7.063939e+01,1.676231e+01,-2.160000e+01,6.120000e+01,7.460000e+01,8.190000e+01,1.747000e+02
wind_mph,166838.0,7.897189e+00,6.867916e+00,2.200000e+00,3.800000e+00,6.700000e+00,1.070000e+01,1.841200e+03
wind_kph,166838.0,1.271312e+01,1.104925e+01,3.600000e+00,6.100000e+00,1.080000e+01,1.730000e+01,2.963200e+03
wind_degree,166838.0,1.701742e+02,1.033293e+02,1.000000e+00,8.100000e+01,1.640000e+02,2.570000e+02,3.600000e+02
pressure_mb,166838.0,1.013992e+03,9.943215e+00,7.710000e+02,1.010000e+03,1.014000e+03,1.018000e+03,3.006000e+03
pressure_in,166838.0,2.994264e+01,2.935572e-01,2.276000e+01,2.983000e+01,2.993000e+01,3.006000e+01,8.877000e+01
precip_mm,166838.0,1.321403e-01,6.092790e-01,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e-02,7.452000e+01
precip_in,166838.0,5.008571e-03,2.406154e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.930000e+00
humidity,166838.0,6.700827e+01,2.346357e+01,2.000000e+00,5.200000e+01,7.200000e+01,8.500000e+01,1.000000e+02
cloud,166838.0,3.999026e+01,3.466446e+01,0.000000e+00,0.000000e+00,2.800000e+01,7.500000e+01,1.000000e+02
feels_like_celsius,166838.0,2.219028e+01,1.119741e+01,-4.000000e+01,1.600000e+01,2.500000e+01,2.980000e+01,8.130000e+01
feels_like_fahrenheit,166838.0,7.193800e+01,2.015331e+01,-4.000000e+01,6.080000e+01,7.690000e+01,8.560000e+01,1.783000e+02
visibility_km,166838.0,9.505766e+00,2.657660e+00,0.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01,3.200000e+01
visibility_miles,166838.0,5.620572e+00,1.658335e+00,0.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,1.900000e+01
uv_index,166838.0,3.087832e+00,3.489764e+00,0.000000e+00,0.000000e+00,1.400000e+00,5.900000e+00,1.630000e+01
gust_mph,166838.0,1.126102e+01,8.301304e+00,2.200000e+00,6.300000e+00,9.400000e+00,1.500000e+01,1.845700e+03
gust_kph,166838.0,1.812479e+01,1.335953e+01,3.600000e+00,1.010000e+01,1.520000e+01,2.410000e+01,2.970400e+03
air_quality_Carbon_Monoxide,166838.0,4.182160e+02,6.993610e+02,-9.999000e+03,1.758500e+02,2.664000e+02,4.236500e+02,3.887940e+04
air_quality_Ozone,166838.0,5.787680e+01,3.116078e+01,0.000000e+00,3.800000e+01,5.400000e+01,7.300000e+01,4.807000e+02
air_quality_Nitrogen_dioxide,166838.0,1.395932e+01,2.222528e+01,0.000000e+00,1.700000e+00,5.450000e+00,1.590000e+01,4.277000e+02
air_quality_Sulphur_dioxide,166838.0,9.570608e+00,3.265092e+01,-9.999000e+03,1.050000e+00,2.300000e+00,7.550000e+00,5.213300e+02
air_quality_PM2.5,166838.0,2.266317e+01,3.448446e+01,1.000000e-01,6.750000e+00,1.313500e+01,2.580000e+01,1.614100e+03
air_quality_PM10,166838.0,4.543691e+01,1.406580e+02,-1.848150e+03,9.550000e+00,1.865000e+01,3.880000e+01,6.037290e+03
air_quality_us-epa-index,166838.0,1.644056e+00,9.122352e-01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,6.000000e+00
air_quality_gb-defra-index,166838.0,2.478980e+00,2.356531e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,1.000000e+01
moon_illumination,166838.0,5.000449e+01,3.503328e+01,0.000000e+00,1.500000e+01,5.000000e+01,8.500000e+01,1.000000e+02

In [7]:
## Remove Duplicates
df = df.drop_duplicates().reset_index(drop=True)

In [8]:
## Clean Column Names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [9]:
## Convert date time
df['last_updated'] = pd.to_datetime(
    df['last_updated'],
    errors='coerce'
)

In [10]:
## Clean text columns
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [11]:

df['wind_direction'] = df['wind_direction'].str.upper()
df['country'] = df['country'].str.title()
df['location_name'] = df['location_name'].str.title()

In [12]:
## Validate geographical values
df.loc[
    (df['latitude'] < -90) | (df['latitude'] > 90),
    'latitude'
] = np.nan

df.loc[
    (df['longitude'] < -180) | (df['longitude'] > 180),
    'longitude'
] = np.nan

In [13]:
## Clean Weather Values
df.loc[
    (df['humidity'] < 0) | (df['humidity'] > 100),
    'humidity'
] = np.nan

In [14]:

df.loc[
    (df['cloud'] < 0) | (df['cloud'] > 100),
    'cloud'
] = np.nan

In [15]:
df.loc[df['precip_mm'] < 0, 'precip_mm'] = np.nan
df.loc[df['precip_in'] < 0, 'precip_in'] = np.nan

In [16]:
df.loc[
    (df['wind_degree'] < 0) | (df['wind_degree'] > 360),
    'wind_degree'
] = np.nan

In [17]:
## Clean clearly invalid air-quality values
air_quality_columns = [
    'air_quality_carbon_monoxide',
    'air_quality_ozone',
    'air_quality_nitrogen_dioxide',
    'air_quality_sulphur_dioxide',
    'air_quality_pm2.5',
    'air_quality_pm10'
]

for col in air_quality_columns:
    df.loc[df[col] < 0, col] = np.nan

In [18]:
## Clean Unrealistic Pressure
df.loc[
    (df['pressure_mb'] < 800) |
    (df['pressure_mb'] > 1100),
    'pressure_mb'
] = np.nan

In [19]:
## Clean Unrealistic Wind Values
df.loc[df['wind_mph'] > 150, 'wind_mph'] = np.nan
df.loc[df['wind_kph'] > 240, 'wind_kph'] = np.nan

df.loc[df['gust_mph'] > 150, 'gust_mph'] = np.nan
df.loc[df['gust_kph'] > 240, 'gust_kph'] = np.nan

In [20]:
## Validate air quality indexes
df.loc[
    (df['air_quality_us-epa-index'] < 1) |
    (df['air_quality_us-epa-index'] > 6),
    'air_quality_us-epa-index'
] = np.nan

In [21]:
df.loc[
    (df['air_quality_gb-defra-index'] < 1) |
    (df['air_quality_gb-defra-index'] > 10),
    'air_quality_gb-defra-index'
] = np.nan

In [22]:
Validate moon illumination
df.loc[
    (df['moon_illumination'] < 0) |
    (df['moon_illumination'] > 100),
    'moon_illumination'
] = np.nan

In [23]:
## Handle missing values
df.isnull().sum().sort_values(ascending=False)

pressure_mb                     5
wind_kph                        3
gust_mph                        3
gust_kph                        3
wind_mph                        3
air_quality_pm10                2
air_quality_carbon_monoxide     1
air_quality_sulphur_dioxide     1
air_quality_pm2.5               0
uv_index                        0
air_quality_ozone               0
air_quality_nitrogen_dioxide    0
country                         0
visibility_km                   0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
visibility_miles                0
feels_like_celsius              0
feels_like_fahrenheit           0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_degree                     0
wind_direction                  0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
moon_illumination               0
dtype: int64

In [24]:
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

In [25]:
## Cross Check
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 166838
Columns: 41

In [26]:
print("Missing values:")
print(df.isnull().sum().sum())

Missing values:
0

In [27]:
print("Duplicate rows:")
print(df.duplicated().sum())

Duplicate rows:
0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166838 entries, 0 to 166837
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       166838 non-null  object
 1   location_name                 166838 non-null  object
 2   latitude                      166838 non-null  float64
 3   longitude                     166838 non-null  float64
 4   timezone                      166838 non-null  object
 5   last_updated_epoch            166838 non-null  int64
 6   last_updated                  166838 non-null  datetime64[ns]
 7   temperature_celsius           166838 non-null  float64
 8   temperature_fahrenheit        166838 non-null  float64
 9   condition_text                166838 non-null  object
 10  wind_mph                      166838 non-null  float64
 11  wind_kph                      166838 non-null  float64
 12  wind_degree                   166838 non-null  float64
 13  wind_direction                166838 non-null  object
 14  pressure_mb                   166838 non-null  float64
 15  pressure_in                   166838 non-null  float64
 16  precip_mm                     166838 non-null  float64
 17  precip_in                     166838 non-null  float64
 18  humidity                      166838 non-null  float64
 19  cloud                         166838 non-null  float64
 20  feels_like_celsius            166838 non-null  float64
 21  feels_like_fahrenheit         166838 non-null  float64
 22  visibility_km                 166838 non-null  float64
 23  visibility_miles              166838 non-null  float64
 24  uv_index                      166838 non-null  float64
 25  gust_mph                      166838 non-null  float64
 26  gust_kph                      166838 non-null  float64
 27  air_quality_carbon_monoxide   166838 non-null  float64
 28  air_quality_ozone             166838 non-null  float64
 29  air_quality_nitrogen_dioxide  166838 non-null  float64
 30  air_quality_sulphur_dioxide   166838 non-null  float64
 31  air_quality_pm2.5             166838 non-null  float64
 32  air_quality_pm10              166838 non-null  float64
 33  air_quality_us-epa-index      166838 non-null  float64
 34  air_quality_gb-defra-index    166838 non-null  float64
 35  sunrise                       166838 non-null  object
 36  sunset                        166838 non-null  object
 37  moonrise                      166838 non-null  object
 38  moonset                       166838 non-null  object
 39  moon_phase                    166838 non-null  object
 40  moon_illumination             166838 non-null  float64
dtypes: datetime64[ns](1), float64(29), int64(1), object(10)
memory usage: 52.2+ MB

In [31]:
## Save the cleaned file
df.to_csv(
    "Global_Weather_Repository_Cleaned.csv",
    index=False
)